/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2017-03-12 01:48:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.resource.view.template.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<footer id=\"footer\" class=\"footer color-bg\">\r\n");
      out.write("  <div class=\"footer-bottom\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-xs-12 col-sm-6 col-md-3\">\r\n");
      out.write("          <div class=\"module-heading\">\r\n");
      out.write("            <h4 class=\"module-title\">Contact Us</h4>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.module-heading -->\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"module-body\">\r\n");
      out.write("            <ul class=\"toggle-footer\" style=\"\">\r\n");
      out.write("              <li class=\"media\">\r\n");
      out.write("                <div class=\"pull-left\"> <span class=\"icon fa-stack fa-lg\"> <i class=\"fa fa-map-marker fa-stack-1x fa-inverse\"></i> </span> </div>\r\n");
      out.write("                <div class=\"media-body\">\r\n");
      out.write("                  <p>ThemesGround, 789 Main rd, Anytown, CA 12345 USA</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"media\">\r\n");
      out.write("                <div class=\"pull-left\"> <span class=\"icon fa-stack fa-lg\"> <i class=\"fa fa-mobile fa-stack-1x fa-inverse\"></i> </span> </div>\r\n");
      out.write("                <div class=\"media-body\">\r\n");
      out.write("                  <p>+(888) 123-4567<br>\r\n");
      out.write("                    +(888) 456-7890</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"media\">\r\n");
      out.write("                <div class=\"pull-left\"> <span class=\"icon fa-stack fa-lg\"> <i class=\"fa fa-envelope fa-stack-1x fa-inverse\"></i> </span> </div>\r\n");
      out.write("                <div class=\"media-body\"> <span><a href=\"#\">flipmart@themesground.com</a></span> </div>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.module-body --> \r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.col -->\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-xs-12 col-sm-6 col-md-3\">\r\n");
      out.write("          <div class=\"module-heading\">\r\n");
      out.write("            <h4 class=\"module-title\">Customer Service</h4>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.module-heading -->\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"module-body\">\r\n");
      out.write("            <ul class='list-unstyled'>\r\n");
      out.write("              <li class=\"first\"><a href=\"#\" title=\"Contact us\">My Account</a></li>\r\n");
      out.write("              <li><a href=\"#\" title=\"About us\">Order History</a></li>\r\n");
      out.write("              <li><a href=\"#\" title=\"faq\">FAQ</a></li>\r\n");
      out.write("              <li><a href=\"#\" title=\"Popular Searches\">Specials</a></li>\r\n");
      out.write("              <li class=\"last\"><a href=\"#\" title=\"Where is my order?\">Help Center</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.module-body --> \r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.col -->\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-xs-12 col-sm-6 col-md-3\">\r\n");
      out.write("          <div class=\"module-heading\">\r\n");
      out.write("            <h4 class=\"module-title\">Corporation</h4>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.module-heading -->\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"module-body\">\r\n");
      out.write("            <ul class='list-unstyled'>\r\n");
      out.write("              <li class=\"first\"><a title=\"Your Account\" href=\"#\">About us</a></li>\r\n");
      out.write("              <li><a title=\"Information\" href=\"#\">Customer Service</a></li>\r\n");
      out.write("              <li><a title=\"Addresses\" href=\"#\">Company</a></li>\r\n");
      out.write("              <li><a title=\"Addresses\" href=\"#\">Investor Relations</a></li>\r\n");
      out.write("              <li class=\"last\"><a title=\"Orders History\" href=\"#\">Advanced Search</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.module-body --> \r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.col -->\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-xs-12 col-sm-6 col-md-3\">\r\n");
      out.write("          <div class=\"module-heading\">\r\n");
      out.write("            <h4 class=\"module-title\">Why Choose Us</h4>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.module-heading -->\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"module-body\">\r\n");
      out.write("            <ul class='list-unstyled'>\r\n");
      out.write("              <li class=\"first\"><a href=\"#\" title=\"About us\">Shopping Guide</a></li>\r\n");
      out.write("              <li><a href=\"#\" title=\"Blog\">Blog</a></li>\r\n");
      out.write("              <li><a href=\"#\" title=\"Company\">Company</a></li>\r\n");
      out.write("              <li><a href=\"#\" title=\"Investor Relations\">Investor Relations</a></li>\r\n");
      out.write("              <li class=\" last\"><a href=\"contact-us.html\" title=\"Suppliers\">Contact Us</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.module-body --> \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"copyright-bar\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"col-xs-12 col-sm-6 no-padding social\">\r\n");
      out.write("        <ul class=\"link\">\r\n");
      out.write("          <li class=\"fb pull-left\"><a target=\"_blank\" rel=\"nofollow\" href=\"#\" title=\"Facebook\"></a></li>\r\n");
      out.write("          <li class=\"tw pull-left\"><a target=\"_blank\" rel=\"nofollow\" href=\"#\" title=\"Twitter\"></a></li>\r\n");
      out.write("          <li class=\"googleplus pull-left\"><a target=\"_blank\" rel=\"nofollow\" href=\"#\" title=\"GooglePlus\"></a></li>\r\n");
      out.write("          <li class=\"rss pull-left\"><a target=\"_blank\" rel=\"nofollow\" href=\"#\" title=\"RSS\"></a></li>\r\n");
      out.write("          <li class=\"pintrest pull-left\"><a target=\"_blank\" rel=\"nofollow\" href=\"#\" title=\"PInterest\"></a></li>\r\n");
      out.write("          <li class=\"linkedin pull-left\"><a target=\"_blank\" rel=\"nofollow\" href=\"#\" title=\"Linkedin\"></a></li>\r\n");
      out.write("          <li class=\"youtube pull-left\"><a target=\"_blank\" rel=\"nofollow\" href=\"#\" title=\"Youtube\"></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-xs-12 col-sm-6 no-padding\">\r\n");
      out.write("        <div class=\"clearfix payment-methods\">\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><img src=\"resource/view/template/assets/images/payments/1.png\" alt=\"\"></li>\r\n");
      out.write("            <li><img src=\"resource/view/template/assets/images/payments/2.png\" alt=\"\"></li>\r\n");
      out.write("            <li><img src=\"resource/view/template/assets/images/payments/3.png\" alt=\"\"></li>\r\n");
      out.write("            <li><img src=\"resource/view/template/assets/images/payments/4.png\" alt=\"\"></li>\r\n");
      out.write("            <li><img src=\"resource/view/template/assets/images/payments/5.png\" alt=\"\"></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.payment-methods --> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
