/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2017-03-12 01:48:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.resource.view.template.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<header class=\"header-style-1\"> \r\n");
      out.write("  \r\n");
      out.write("  <!-- ============================================== TOP MENU ============================================== -->\r\n");
      out.write("  <div class=\"navbar navbar-fixed-top top-bar animate-dropdown\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"header-top-inner\">\r\n");
      out.write("        <div class=\"cnt-account\">\r\n");
      out.write("          <ul class=\"list-unstyled\">\r\n");
      out.write("            <li><a href=\"#\"><i class=\"icon fa fa-user\"></i>My Account</a></li>\r\n");
      out.write("            <li><a href=\"#\"><i class=\"icon fa fa-heart\"></i>Wishlist</a></li>\r\n");
      out.write("            <li><a href=\"#\"><i class=\"icon fa fa-shopping-cart\"></i>My Cart</a></li>\r\n");
      out.write("            <li><a href=\"#\"><i class=\"icon fa fa-check\"></i>Checkout</a></li>\r\n");
      out.write("            <li><a href=\"#\"><i class=\"icon fa fa-lock\"></i>Login</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.cnt-account -->\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"cnt-block\">\r\n");
      out.write("          <ul class=\"list-unstyled list-inline\">\r\n");
      out.write("            <li class=\"dropdown dropdown-small\"> <a href=\"#\" class=\"dropdown-toggle\" data-hover=\"dropdown\" data-toggle=\"dropdown\"><span class=\"value\">USD </span><b class=\"caret\"></b></a>\r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li><a href=\"#\">USD</a></li>\r\n");
      out.write("                <li><a href=\"#\">INR</a></li>\r\n");
      out.write("                <li><a href=\"#\">GBP</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"dropdown dropdown-small\"> <a href=\"#\" class=\"dropdown-toggle\" data-hover=\"dropdown\" data-toggle=\"dropdown\"><span class=\"value\">English </span><b class=\"caret\"></b></a>\r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li><a href=\"#\">English</a></li>\r\n");
      out.write("                <li><a href=\"#\">French</a></li>\r\n");
      out.write("                <li><a href=\"#\">German</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <!-- /.list-unstyled --> \r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.cnt-cart -->\r\n");
      out.write("        <div class=\"clearfix\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- /.header-top-inner --> \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.container --> \r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /.header-top --> \r\n");
      out.write("  <!-- ============================================== TOP MENU : END ============================================== -->\r\n");
      out.write("  <div class=\"main-header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-xs-12 col-sm-12 col-md-3 logo-holder\"> \r\n");
      out.write("          <!-- ============================================================= LOGO ============================================================= -->\r\n");
      out.write("          <div class=\"logo\"> <a href=\"home.html\"> <img src=\"resource/view/template/assets/images/logo.png\" alt=\"logo\"> </a> </div>\r\n");
      out.write("          <!-- /.logo --> \r\n");
      out.write("          <!-- ============================================================= LOGO : END ============================================================= --> </div>\r\n");
      out.write("        <!-- /.logo-holder -->\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-xs-12 col-sm-12 col-md-7 top-search-holder\"> \r\n");
      out.write("          <!-- /.contact-row --> \r\n");
      out.write("          <!-- ============================================================= SEARCH AREA ============================================================= -->\r\n");
      out.write("          <div class=\"search-area\">\r\n");
      out.write("            <form>\r\n");
      out.write("              <div class=\"control-group\">\r\n");
      out.write("                <ul class=\"categories-filter animate-dropdown\">\r\n");
      out.write("                  <li class=\"dropdown\"> <a class=\"dropdown-toggle\"  data-toggle=\"dropdown\" href=\"#\">Categories <b class=\"caret\"></b></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\" role=\"menu\" >\r\n");
      out.write("                      <li class=\"menu-header\">Computer</li>\r\n");
      out.write("                      <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"category.html\">- Clothing</a></li>\r\n");
      out.write("                      <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"category.html\">- Electronics</a></li>\r\n");
      out.write("                      <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"category.html\">- Shoes</a></li>\r\n");
      out.write("                      <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"category.html\">- Watches</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <input class=\"search-field\" placeholder=\"Search here...\" />\r\n");
      out.write("                <a class=\"search-button\" href=\"#\" ></a> </div>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.search-area --> \r\n");
      out.write("          <!-- ============================================================= SEARCH AREA : END ============================================================= --> </div>\r\n");
      out.write("        <!-- /.top-search-holder -->\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-xs-12 col-sm-12 col-md-2 animate-dropdown top-cart-row\"> \r\n");
      out.write("          <!-- ============================================================= SHOPPING CART DROPDOWN ============================================================= -->\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"dropdown dropdown-cart\"> <a href=\"#\" class=\"dropdown-toggle lnk-cart\" data-toggle=\"dropdown\">\r\n");
      out.write("            <div class=\"items-cart-inner\">\r\n");
      out.write("              <div class=\"basket\"> <i class=\"glyphicon glyphicon-shopping-cart\"></i> </div>\r\n");
      out.write("              <div class=\"basket-item-count\"><span class=\"count\">2</span></div>\r\n");
      out.write("              <div class=\"total-price-basket\"> <span class=\"lbl\">cart -</span> <span class=\"total-price\"> <span class=\"sign\">$</span><span class=\"value\">600.00</span> </span> </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("              <li>\r\n");
      out.write("                <div class=\"cart-item product-summary\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xs-4\">\r\n");
      out.write("                      <div class=\"image\"> <a href=\"detail.html\"><img src=\"resource/view/template/assets/images/cart.jpg\" alt=\"\"></a> </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xs-7\">\r\n");
      out.write("                      <h3 class=\"name\"><a href=\"index.php?page-detail\">Simple Product</a></h3>\r\n");
      out.write("                      <div class=\"price\">$600.00</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xs-1 action\"> <a href=\"#\"><i class=\"fa fa-trash\"></i></a> </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.cart-item -->\r\n");
      out.write("                <div class=\"clearfix\"></div>\r\n");
      out.write("                <hr>\r\n");
      out.write("                <div class=\"clearfix cart-total\">\r\n");
      out.write("                  <div class=\"pull-right\"> <span class=\"text\">Sub Total :</span><span class='price'>$600.00</span> </div>\r\n");
      out.write("                  <div class=\"clearfix\"></div>\r\n");
      out.write("                  <a href=\"checkout.html\" class=\"btn btn-upper btn-primary btn-block m-t-20\">Checkout</a> </div>\r\n");
      out.write("                <!-- /.cart-total--> \r\n");
      out.write("                \r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <!-- /.dropdown-menu--> \r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.dropdown-cart --> \r\n");
      out.write("          \r\n");
      out.write("          <!-- ============================================================= SHOPPING CART DROPDOWN : END============================================================= --> </div>\r\n");
      out.write("        <!-- /.top-cart-row --> \r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- /.row --> \r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.container --> \r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /.main-header --> \r\n");
      out.write("  \r\n");
      out.write("  <!-- ============================================== NAVBAR ============================================== -->\r\n");
      out.write("  <div class=\"header-nav animate-dropdown\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"yamm navbar navbar-default\" role=\"navigation\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("       <button data-target=\"#mc-horizontal-menu-collapse\" data-toggle=\"collapse\" class=\"navbar-toggle collapsed\" type=\"button\"> \r\n");
      out.write("       <span class=\"sr-only\">Toggle navigation</span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav-bg-class\">\r\n");
      out.write("          <div class=\"navbar-collapse collapse\" id=\"mc-horizontal-menu-collapse\">\r\n");
      out.write("            <div class=\"nav-outer\">\r\n");
      out.write("              <ul class=\"nav navbar-nav\">\r\n");
      out.write("                <li class=\"active dropdown yamm-fw\"> <a href=\"home.html\" data-hover=\"dropdown\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Home</a> </li>\r\n");
      out.write("                <li class=\"dropdown yamm mega-menu\"> <a href=\"home.html\" data-hover=\"dropdown\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Clothing</a>\r\n");
      out.write("                  <ul class=\"dropdown-menu container\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <div class=\"yamm-content \">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                          <div class=\"col-xs-12 col-sm-6 col-md-2 col-menu\">\r\n");
      out.write("                            <h2 class=\"title\">Men</h2>\r\n");
      out.write("                            <ul class=\"links\">\r\n");
      out.write("                              <li><a href=\"#\">Dresses</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Shoes </a></li>\r\n");
      out.write("                              <li><a href=\"#\">Jackets</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Sunglasses</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Sport Wear</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Blazers</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Shirts</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <!-- /.col -->\r\n");
      out.write("                          \r\n");
      out.write("                          <div class=\"col-xs-12 col-sm-6 col-md-2 col-menu\">\r\n");
      out.write("                            <h2 class=\"title\">Women</h2>\r\n");
      out.write("                            <ul class=\"links\">\r\n");
      out.write("                              <li><a href=\"#\">Handbags</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Jwellery</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Swimwear </a></li>\r\n");
      out.write("                              <li><a href=\"#\">Tops</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Flats</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Shoes</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Winter Wear</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <!-- /.col -->\r\n");
      out.write("                          \r\n");
      out.write("                          <div class=\"col-xs-12 col-sm-6 col-md-2 col-menu\">\r\n");
      out.write("                            <h2 class=\"title\">Boys</h2>\r\n");
      out.write("                            <ul class=\"links\">\r\n");
      out.write("                              <li><a href=\"#\">Toys & Games</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Jeans</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Shirts</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Shoes</a></li>\r\n");
      out.write("                              <li><a href=\"#\">School Bags</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Lunch Box</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Footwear</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <!-- /.col -->\r\n");
      out.write("                          \r\n");
      out.write("                          <div class=\"col-xs-12 col-sm-6 col-md-2 col-menu\">\r\n");
      out.write("                            <h2 class=\"title\">Girls</h2>\r\n");
      out.write("                            <ul class=\"links\">\r\n");
      out.write("                              <li><a href=\"#\">Sandals </a></li>\r\n");
      out.write("                              <li><a href=\"#\">Shorts</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Dresses</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Jwellery</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Bags</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Night Dress</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Swim Wear</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <!-- /.col -->\r\n");
      out.write("                          \r\n");
      out.write("                          <div class=\"col-xs-12 col-sm-6 col-md-4 col-menu banner-image\"> <img class=\"img-responsive\" src=\"resource/view/template/assets/images/banners/top-menu-banner.jpg\" alt=\"\"> </div>\r\n");
      out.write("                          <!-- /.yamm-content --> \r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"dropdown mega-menu\"> \r\n");
      out.write("                <a href=\"category.html\"  data-hover=\"dropdown\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Electronics <span class=\"menu-label hot-menu hidden-xs\">hot</span> </a>\r\n");
      out.write("                  <ul class=\"dropdown-menu container\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <div class=\"yamm-content\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                          <div class=\"col-xs-12 col-sm-12 col-md-2 col-menu\">\r\n");
      out.write("                            <h2 class=\"title\">Laptops</h2>\r\n");
      out.write("                            <ul class=\"links\">\r\n");
      out.write("                              <li><a href=\"#\">Gaming</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Laptop Skins</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Apple</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Dell</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Lenovo</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Microsoft</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Asus</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Adapters</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Batteries</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Cooling Pads</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <!-- /.col -->\r\n");
      out.write("                          \r\n");
      out.write("                          <div class=\"col-xs-12 col-sm-12 col-md-2 col-menu\">\r\n");
      out.write("                            <h2 class=\"title\">Desktops</h2>\r\n");
      out.write("                            <ul class=\"links\">\r\n");
      out.write("                              <li><a href=\"#\">Routers & Modems</a></li>\r\n");
      out.write("                              <li><a href=\"#\">CPUs, Processors</a></li>\r\n");
      out.write("                              <li><a href=\"#\">PC Gaming Store</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Graphics Cards</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Components</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Webcam</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Memory (RAM)</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Motherboards</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Keyboards</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Headphones</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <!-- /.col -->\r\n");
      out.write("                          \r\n");
      out.write("                          <div class=\"col-xs-12 col-sm-12 col-md-2 col-menu\">\r\n");
      out.write("                            <h2 class=\"title\">Cameras</h2>\r\n");
      out.write("                            <ul class=\"links\">\r\n");
      out.write("                              <li><a href=\"#\">Accessories</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Binoculars</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Telescopes</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Camcorders</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Digital</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Film Cameras</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Flashes</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Lenses</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Surveillance</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Tripods</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <!-- /.col -->\r\n");
      out.write("                          <div class=\"col-xs-12 col-sm-12 col-md-2 col-menu\">\r\n");
      out.write("                            <h2 class=\"title\">Mobile Phones</h2>\r\n");
      out.write("                            <ul class=\"links\">\r\n");
      out.write("                              <li><a href=\"#\">Apple</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Samsung</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Lenovo</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Motorola</a></li>\r\n");
      out.write("                              <li><a href=\"#\">LeEco</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Asus</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Acer</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Accessories</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Headphones</a></li>\r\n");
      out.write("                              <li><a href=\"#\">Memory Cards</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"col-xs-12 col-sm-12 col-md-4 col-menu custom-banner\"> <a href=\"#\"><img alt=\"\" src=\"resource/view/template/assets/images/banners/banner-side.png\"></a> </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- /.row --> \r\n");
      out.write("                      </div>\r\n");
      out.write("                      <!-- /.yamm-content --> </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"dropdown hidden-sm\"> <a href=\"category.html\">Health & Beauty <span class=\"menu-label new-menu hidden-xs\">new</span> </a> </li>\r\n");
      out.write("                <li class=\"dropdown hidden-sm\"> <a href=\"category.html\">Watches</a> </li>\r\n");
      out.write("                <li class=\"dropdown\"> <a href=\"contact.html\">Jewellery</a> </li>\r\n");
      out.write("                <li class=\"dropdown\"> <a href=\"contact.html\">Shoes</a> </li>\r\n");
      out.write("                <li class=\"dropdown\"> <a href=\"contact.html\">Kids & Girls</a> </li>\r\n");
      out.write("                <li class=\"dropdown\"> <a href=\"#\" class=\"dropdown-toggle\" data-hover=\"dropdown\" data-toggle=\"dropdown\">Pages</a>\r\n");
      out.write("                  <ul class=\"dropdown-menu pages\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <div class=\"yamm-content\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                          <div class=\"col-xs-12 col-menu\">\r\n");
      out.write("                            <ul class=\"links\">\r\n");
      out.write("                              <li><a href=\"homePage\">Home</a></li>\r\n");
      out.write("                              <li><a href=\"category\">Category</a></li>\r\n");
      out.write("                              <li><a href=\"detail.html\">Detail</a></li>\r\n");
      out.write("                              <li><a href=\"shopping-cart\">Shopping Cart Summary</a></li>\r\n");
      out.write("                              <li><a href=\"check\tout\">Checkout</a></li>\r\n");
      out.write("                              <li><a href=\"blog.html\">Blog</a></li>\r\n");
      out.write("                              <li><a href=\"blog-details.html\">Blog Detail</a></li>\r\n");
      out.write("                              <li><a href=\"contact\">Contact</a></li>\r\n");
      out.write("                              <li><a href=\"sign-in\">Sign In</a></li>\r\n");
      out.write("                              <li><a href=\"my-wishlist.html\">Wishlist</a></li>\r\n");
      out.write("                              <li><a href=\"terms-conditions.html\">Terms and Condition</a></li>\r\n");
      out.write("                              <li><a href=\"track-orders.html\">Track Orders</a></li>\r\n");
      out.write("                              <li><a href=\"product-comparison.html\">Product-Comparison</a></li>\r\n");
      out.write("                              <li><a href=\"faq.html\">FAQ</a></li>\r\n");
      out.write("                              <li><a href=\"404.html\">404</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("             \r\n");
      out.write("              </ul>\r\n");
      out.write("              <!-- /.navbar-nav -->\r\n");
      out.write("              <div class=\"clearfix\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.nav-outer --> \r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.navbar-collapse --> \r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.nav-bg-class --> \r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- /.navbar-default --> \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.container-class --> \r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /.header-nav --> \r\n");
      out.write("  <!-- ============================================== NAVBAR : END ============================================== --> \r\n");
      out.write("</header>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
