/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2017-03-03 12:07:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.template.homepage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("   <!--FOOTER-->\r\n");
      out.write("<section id=\"footer\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"footer-top-container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-3 col-sm-4 col-xs-12\">\r\n");
      out.write("                    <div class=\"footer-top-left\">\r\n");
      out.write("                        <div class=\"newletter-top-left\">\r\n");
      out.write("                            <h2>Send-Email</h2>\r\n");
      out.write("                            <p>Contact us by your email.We will feedback you soon.Thank you!!!</p>\r\n");
      out.write("                            <form action=\"#\">\r\n");
      out.write("                                <div class=\"form-group newletter-form-group\">\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control newletter-form\" placeholder=\"Enter your email\">\r\n");
      out.write("                                    <input type=\"submit\" class=\"newletter-btn\" name=\"Submit\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"about-us\">\r\n");
      out.write("                            <h2>Ms-Shop</h2>\r\n");
      out.write("                            <p>Yolo-ndmdmdk</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"follow-us\">\r\n");
      out.write("                            <h2>Follow us By</h2>\r\n");
      out.write("                            <ul class=\"follow-us-social\">\r\n");
      out.write("                                <li><a href=\"\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"\"><i class=\"fa fa-rss\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-9 col-md-9 col-sm-8 col-xs-12\">\r\n");
      out.write("                    <div class=\"footer-top-right-left\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-lg-4 col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("                                <div class=\"block\" style=\"margin-bottom:50px;\">\r\n");
      out.write("                                    <h2>Dành cho người mua</h2>\r\n");
      out.write("                                    <p>Bảo vệ người mua</p>\r\n");
      out.write("                                    <p>Quy định đối với người mua</p>\r\n");
      out.write("                                    <p>Giải quyết khiếu nại</p>\r\n");
      out.write("                                    <p>Câu hỏi</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-4 col-md-4 col-sm-6 col-xs-12\">\r\n");
      out.write("                                <div class=\"store-information\">\r\n");
      out.write("                                    <h2>Shop_Information</h2>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"left-icon\">\r\n");
      out.write("                                            <i class=\"fa fa-map-marker\"></i>\r\n");
      out.write("                                            </div>    \r\n");
      out.write("                                            <div class=\"info-title\">\r\n");
      out.write("                                                <p>My shop-...</p>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"left-icon\">\r\n");
      out.write("                                                <i class=\"fa fa-phone\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"info-title call\">\r\n");
      out.write("                                                <p>Call us: 01665102292</p>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <div class=\"left-icon\">\r\n");
      out.write("                                                <i class=\"fa fa-envelope-o\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"info-title\">\r\n");
      out.write("                                                <p>Email:<a href=\"#\"></a><i class=\"fa fa-angle-double-right\"></i></p>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-4 col-md-4 col-sm-6 col-xs-12 footer-map-add\">\r\n");
      out.write("                                <div class=\"footer-address\">\r\n");
      out.write("                                    <h2 class=\"content-paget-title-item\" style=\"color:white\">Địa chỉ cửa hàng</h2>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"footer-map\">\r\n");
      out.write("                                    <img src=\"resource/images/banner/map.png\" style=\"width:100%\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("    <!--END FOOTER-->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
